import { DEMO_AGENT_ID, DEMO_ORGANIZATION_ID } from './demo-tenant.js';
import {
  MONETIZATION_WORKED_EXAMPLE,
  type MonetizationEvent,
} from '../domain/monetization.js';
import { buildMonetizationEvent } from '../engine/monetization-engine.js';

/**
 * Sandbox monetization ledger for the demo tenant.
 *
 * Covers every revenue source. Amounts are USD minor units unless noted. Nothing here moved money.
 */
export function demoMonetizationEvents(nowMs: number): readonly MonetizationEvent[] {
  const at = (daysAgo: number, hour = 12): string =>
    new Date(nowMs - daysAgo * 86_400_000 + hour * 3_600_000).toISOString();

  return [
    buildMonetizationEvent({
      id: 'mon_demo_fx_100k',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(2),
      transactionType: 'fiat_comparison',
      revenueSource: 'traditional_fx_routing_fee',
      rail: 'bank_fx',
      providerId: 'sandbox-northgate-bank',
      providerName: 'Northgate Bank',
      currency: 'USD',
      asset: 'USD',
      destinationAsset: 'KRW',
      agentId: null,
      tpvMinorUnits: MONETIZATION_WORKED_EXAMPLE.tpvMinorUnits,
      providerCostMinorUnits: MONETIZATION_WORKED_EXAMPLE.providerCostMinorUnits,
      platformRevenueMinorUnits: MONETIZATION_WORKED_EXAMPLE.platformRevenueMinorUnits,
      partnerCommissionMinorUnits: MONETIZATION_WORKED_EXAMPLE.partnerCommissionMinorUnits,
    }),
    buildMonetizationEvent({
      id: 'mon_demo_payment',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(7),
      transactionType: 'fiat_comparison',
      revenueSource: 'payment_routing_fee',
      rail: 'payment_institution',
      providerId: 'sandbox-veridian-payments',
      providerName: 'Veridian Payments',
      currency: 'USD',
      asset: 'USD',
      destinationAsset: 'EUR',
      agentId: null,
      tpvMinorUnits: '25000000',
      providerCostMinorUnits: '75000',
      platformRevenueMinorUnits: '40000',
    }),
    buildMonetizationEvent({
      id: 'mon_demo_stablecoin',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(14),
      transactionType: 'multi_rail_quote',
      revenueSource: 'stablecoin_routing_fee',
      rail: 'stablecoin_settlement',
      providerId: 'sandbox-solstice-settlement',
      providerName: 'Solstice Settlement',
      currency: 'USD',
      asset: 'USD',
      destinationAsset: 'USDC',
      agentId: null,
      tpvMinorUnits: '8000000',
      providerCostMinorUnits: '16000',
      platformRevenueMinorUnits: '12000',
    }),
    buildMonetizationEvent({
      id: 'mon_demo_defi',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(14, 15),
      transactionType: 'multi_rail_quote',
      revenueSource: 'defi_routing_fee',
      rail: 'dex_liquidity',
      providerId: 'sandbox-helix-amm',
      providerName: 'Helix AMM',
      currency: 'USD',
      asset: 'USDC',
      destinationAsset: 'USDT',
      agentId: null,
      tpvMinorUnits: '5000000',
      providerCostMinorUnits: '18000',
      platformRevenueMinorUnits: '8000',
    }),
    buildMonetizationEvent({
      id: 'mon_demo_liquidity',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(21),
      transactionType: 'multi_rail_quote',
      revenueSource: 'liquidity_routing_fee',
      rail: 'liquidity_provider',
      providerId: 'sandbox-aperture-liquidity',
      providerName: 'Aperture Liquidity',
      currency: 'USD',
      asset: 'USD',
      destinationAsset: 'JPY',
      agentId: null,
      tpvMinorUnits: '15000000',
      providerCostMinorUnits: '45000',
      platformRevenueMinorUnits: '24000',
    }),
    buildMonetizationEvent({
      id: 'mon_demo_volume',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(7, 16),
      transactionType: 'fiat_comparison',
      revenueSource: 'enterprise_volume_pricing',
      rail: 'bank_fx',
      providerId: 'sandbox-northgate-bank',
      providerName: 'Northgate Bank',
      currency: 'USD',
      asset: 'USD',
      destinationAsset: 'KRW',
      agentId: null,
      tpvMinorUnits: '10000000',
      providerCostMinorUnits: '28000',
      platformRevenueMinorUnits: '4000',
    }),
    buildMonetizationEvent({
      id: 'mon_demo_agent',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(2, 18),
      transactionType: 'agent_payment',
      revenueSource: 'ai_agent_payment_fee',
      rail: 'payment_institution',
      providerId: 'sandbox-veridian-payments',
      providerName: 'Veridian Payments',
      currency: 'USD',
      asset: 'USD',
      destinationAsset: 'KRW',
      agentId: DEMO_AGENT_ID,
      tpvMinorUnits: '100000',
      providerCostMinorUnits: '400',
      platformRevenueMinorUnits: '200',
    }),
    buildMonetizationEvent({
      id: 'mon_demo_subscription',
      organizationId: DEMO_ORGANIZATION_ID,
      occurredAt: at(1),
      transactionType: 'enterprise_subscription',
      revenueSource: 'enterprise_api_subscription',
      rail: null,
      providerId: null,
      providerName: null,
      currency: 'USD',
      asset: 'USD',
      destinationAsset: null,
      agentId: null,
      tpvMinorUnits: '0',
      providerCostMinorUnits: '0',
      platformRevenueMinorUnits: '200000',
      partnerCommissionMinorUnits: '0',
    }),
  ];
}
